# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'Net_Request_AF' do
    pod 'AFNetworking', '~> 3.0'
    pod 'MBProgressHUD', '~> 1.1.0'
    pod 'OHHTTPStubs'
end
